Captain
anjali790/Cricbuzz pull request #9
Opened 2022-11-21 08:20 UTC by AmitGithub2006

2022-11-22 07:46 UTC, Souvikdeb2612 requested changes

2022-11-22 07:46 UTC, Souvikdeb2612 commented on src/components/Captain/Captain.jsx
> +        {payload.map((entry, index) => (
destructure entry here

2022-11-22 07:46 UTC, Souvikdeb2612 commented on src/components/Captain/Captain.jsx
> +        console.log(res.data);
remove/comment console statements before pushing

2022-11-22 07:46 UTC, Souvikdeb2612 commented on src/components/Card/Card.jsx
> +import Grid from "@mui/material/Grid";
Format imports

2022-11-22 07:46 UTC, Souvikdeb2612 commented on src/components/Card/Card.jsx
> +        console.log(res.data);
same as above

2022-11-22 07:46 UTC, Souvikdeb2612 commented on src/components/Card/Card.jsx
> +            {data.map((item) => (
destructure item here

2022-11-23 09:41 UTC, AmitGithub2006 commented on src/components/Captain/Captain.jsx
> +        {payload.map((entry, index) => (
Issue resolved sir

2022-11-23 17:00 UTC, Souvikdeb2612 approved these changes

2022-11-23 17:00 UTC, merged